/* tslint:disable */
/* eslint-disable */
/**
 * EDM Vandalizações API
 * REST API backend for EDM vandalizações management.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

